### ISSUE TITLE
Breaks Gatsby v3

### ISSUE THREAD

**Issue by fshowalter** [cometkim/gatsby-plugin-linaria#115]
This line: https://github.com/cometkim/gatsby-plugin-linaria/blob/e011a14eda9c7da99ab553aada921dffc2fdf5a6/src/gatsby-node.ts#L53

Created to solve #19 breaks Gatsby v3, which relies on that alias now that they've vendored reach-router. https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#reach-router

Removing the line allows the plugin to work in v3, but I'm not sure if it re-introduces the `styled` problem with Gatsby Link. Regardless, without the change, this will break a lot of folks moving to v3.

**Comment by tadeas22** [comment]
Temporary workaround

`gatsby-node.js`
```javascript
const path = require(`path`)
exports.onCreateWebpackConfig = ({actions,getConfig}) => {
	actions.setWebpackConfig({
		resolve: {
			alias: {
				"@reach/router" : path.dirname(require.resolve(`@gatsbyjs/reach-router/package.json`))
			}
		}
	})
}
```
