### ISSUE TITLE
TS: Using the *** tag in runtime is not supported.

### ISSUE THREAD

**Issue by newash** [cometkim/gatsby-plugin-linaria#13]
I believe this is related to #9.

I have Typescript, with `gatsby-plugin-typescript@2.0.15`.
If I use `v1.1.1` of this plugin, everything works.
If I update to `v1.1.2` I get:
```
WebpackError: Using the "css" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.
  
  - css.js:4 css
    [lib]/[linaria]/lib/core/css.js:4:1
...
```

(in the config I have this plugin listed *after* the Typescript one, as instructed)

**Comment by silvenon** [comment]
Should be working now, please try again.

**Comment by newash** [comment]
:tada: Thank you, it does!

**Comment by guandjoy** [comment]
I've just updated everything and got the same error using v1.1.3. With v1.1.2 and v1.1.1, everything works fine. I don't use typescript. I rechecked on a blank project before posting and got the same error.

**Comment by silvenon** [comment]
Well, isn't hacking webpack configs fun… I'll check it out.

**Comment by silvenon** [comment]
@guandjoy both should work in [v1.1.4](https://github.com/silvenon/gatsby-plugin-linaria/releases/tag/v1.1.4).

**Comment by guandjoy** [comment]
@silvenon Thank you!

**Comment by guandjoy** [comment]
Same error raises when I run:
`gatsby build`
That starts to happen after I've updated Gatsby. Same with all versions of your plugin. Develop mode works fine.

**Comment by nicobohne** [comment]
> Same error raises when I run:
> `gatsby build`
> That starts to happen after I've updated Gatsby. Same with all versions of your plugin. Develop mode works fine.

Same. Dev works fine but build fails

**Comment by silvenon** [comment]
Hm, I wasn't able to reproduce the error. Which versions of Gatsby and gatsby-plugin-linaria are you using?

**Comment by cometkim** [comment]
@silvenon I think this is the same issue with #17

**Comment by cometkim** [comment]
This would be working after #18 merged.

**Comment by guandjoy** [comment]
@silvenon here is the small repo with two branches https://github.com/guandjoy/gatsby-linaria-test
master - latest versions
prev - versions I used when wrote the comment.

But the result is the same. Now it raises the error in both develop and build cases.

**Comment by silvenon** [comment]
Published in [v1.2.2](https://github.com/silvenon/gatsby-plugin-linaria/releases/tag/v1.2.2) 🚀

**Comment by JesseFarebro** [comment]
This issue has resurfaced now that Gatsby supports Typescript out of the box. The TS check doesn't evaluate properly anymore as the internal plugin doesn't seem to add the resolvers in the same way.

https://github.com/silvenon/gatsby-plugin-linaria/blob/e3a40aa7d650c5cde95b5cf27ce89f51f1bce7cb/src/gatsby-node.js#L7-L9

**Comment by cometkim** [comment]
Ah, I almost forgot about it. I will follow up on this issue again this weekend.

**Comment by JM-Mendez** [comment]
I tried to troubleshoot the check, got it to properly configure the loader when typescript was detected, and it still failed. 

The only thing that worked was to manually install and add `gatsby-plugin-typescript` before `gatsby-plugin-linaria` to my config as per the original instructions 🤷

**Comment by cometkim** [comment]
https://github.com/gatsbyjs/gatsby/blob/e50407a235e5e168e875d8a8d701f59084204328/packages/gatsby/src/bootstrap/load-plugins/load.js#L260-L266

GatsbyJS is now supporting typescript plugin, but.. it pushes into the after of the user plugins. As a result, the linaria plugin runs before the typescript loader is attached.

If the user explicitly sets the typescript plugin above it will work, but I need to find a better way.
