### ISSUE TITLE
Request to set option `cacheDirectory`

### ISSUE THREAD

**Issue by tsuki-lab** [cometkim/gatsby-plugin-linaria#135]
I'm not good at English. I'm sorry.

I'm using this plugin to deploy Gatsuby.js to vercel.

However, the cache held by vercel does not contain `.linaria-cache`, and it always causes an error at the first build.
https://vercel.com/docs/build-step#caching

So I wanted to use the option `cacheDirectory` that `linaria/loader` has.
https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#options

I want you to help me to use it more comfortably

**Comment by cometkim** [comment]
Thank you for your contribution @tsuki-lab 

You can now customize loader options since v3.1.0

p.s. English is not a native language to me either :)

**Comment by tsuki-lab** [comment]
@cometkim 
Thank you for checking.
I'm very happy :)
