### ISSUE TITLE
Support for linaria@4.x.x?

### ISSUE THREAD

**Issue by joyfulelement** [cometkim/gatsby-plugin-linaria#153]
Currently `gatsby-plugin-linaria` support `"linaria": "^2.0.0"` as the compatible peer dependency
(https://github.com/cometkim/gatsby-plugin-linaria/blob/main/package.json#L48) and base from `"linaria": "^2.1.0"` (https://github.com/cometkim/gatsby-plugin-linaria/blob/main/package.json#L66) as dev dependency for this package.

Are there any plan to suppor the latest `linaria@4.x.x` versions?

Any guidance for migration path would be much appreciated, thank you

**Comment by cometkim** [comment]
It will support soon
